name: build and publish
on:
  release:
    types: [ published ]
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: "ubuntu-22.04"
    permissions:
      contents: read
      packages: write

    steps:
      # does not need checkout action?
      #- uses: actions/checkout@v4
      
      - name: install postgres dev packages
        run: sudo apt install python3-dev libpq-dev

      - name: Log into ghcr container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up docker buildx for subdirectory build
        uses: docker/setup-buildx-action@v3

      - name: extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:python"
          push: true
          tags: ${{ steps.meta.outputs.tags }},latest
          labels: ${{ steps.meta.outputs.labels }}
